-- Supabase Schema Setup Script for CalorieCraft / Nutrition Tracker

-- 1. Create food_master table
CREATE TABLE IF NOT EXISTS public.food_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT NOT NULL UNIQUE,
    calories FLOAT NOT NULL DEFAULT 0,
    protein FLOAT NOT NULL DEFAULT 0,
    carbs FLOAT NOT NULL DEFAULT 0,
    fat FLOAT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create food_log table
CREATE TABLE IF NOT EXISTS public.food_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    food_name TEXT NOT NULL,
    quantity FLOAT NOT NULL DEFAULT 1,
    calories FLOAT NOT NULL DEFAULT 0,
    protein FLOAT NOT NULL DEFAULT 0,
    carbs FLOAT NOT NULL DEFAULT 0,
    fat FLOAT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create exercise_log table
CREATE TABLE IF NOT EXISTS public.exercise_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    exercise_name TEXT NOT NULL,
    duration_minutes FLOAT NOT NULL DEFAULT 0,
    calories_burned FLOAT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create weight_log table
CREATE TABLE IF NOT EXISTS public.weight_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date DATE NOT NULL UNIQUE DEFAULT CURRENT_DATE,
    weight_kg FLOAT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create users table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security) - Optional: Allow public access for simple setup
ALTER TABLE public.food_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercise_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for food_master" ON public.food_master FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for food_log" ON public.food_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for exercise_log" ON public.exercise_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for weight_log" ON public.weight_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write for users" ON public.users FOR ALL USING (true) WITH CHECK (true);

-- Seed Initial Common Foods into food_master
INSERT INTO public.food_master (food_name, calories, protein, carbs, fat)
VALUES
    ('Chicken Breast (100g cooked)', 165, 31, 0, 3.6),
    ('White Rice (1 cup cooked)', 206, 4.3, 45, 0.4),
    ('Brown Rice (1 cup cooked)', 216, 5, 45, 1.8),
    ('Whole Egg (1 large boiled/poached)', 72, 6.3, 0.4, 4.8),
    ('Oatmeal (1 cup cooked with water)', 158, 6, 27, 3.2),
    ('Banana (1 medium)', 105, 1.3, 27, 0.3),
    ('Apple (1 medium)', 95, 0.5, 25, 0.3),
    ('Whey Protein Powder (1 scoop / 30g)', 120, 24, 3, 1.5),
    ('Salmon Fillet (100g baked)', 206, 22, 0, 12),
    ('Greek Yogurt (170g non-fat)', 100, 17, 6, 0.7),
    ('Almonds (1 oz / 28g)', 164, 6, 6, 14),
    ('Avocado (1 medium)', 240, 3, 12, 22),
    ('Whole Milk (1 cup / 244g)', 149, 8, 12, 8),
    ('Broccoli (1 cup chopped)', 31, 2.5, 6, 0.3)
ON CONFLICT (food_name) DO NOTHING;
